/**
 * LernApp.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeckResponseModel } from './deck-response-model';


export interface ListResponseOfDeckResponseModel { 
    data: Array<DeckResponseModel>;
    totalCount: number;
}

