/**
 * LernApp.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CardResponseModel } from '../model/models';
import { CreateRequestOfCardCreateModel } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiCardsCardCardIdGetRequestParams {
    cardId: string;
}

export interface ApiCardsCardIdDeleteRequestParams {
    cardId: string;
}

export interface ApiCardsDeckIdGetRequestParams {
    deckId: string;
}

export interface ApiCardsPostRequestParams {
    createRequestOfCardCreateModel: CreateRequestOfCardCreateModel;
}


export interface CardServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    apiCardsCardCardIdGet(requestParameters: ApiCardsCardCardIdGetRequestParams, extraHttpRequestParams?: any): Observable<CardResponseModel>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiCardsCardIdDelete(requestParameters: ApiCardsCardIdDeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiCardsDeckIdGet(requestParameters: ApiCardsDeckIdGetRequestParams, extraHttpRequestParams?: any): Observable<Array<CardResponseModel>>;

    /**
     * 
     * 
*/
    apiCardsGet(extraHttpRequestParams?: any): Observable<Array<CardResponseModel>>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiCardsPost(requestParameters: ApiCardsPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
