/**
 * LernApp.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';


export interface ApiCardsCardCardIdGetRequestParams {
    cardId: string;
}

export interface ApiCardsCardIdDeleteRequestParams {
    cardId: string;
}

export interface ApiCardsCardIdPutRequestParams {
    cardId: string;
}

export interface ApiCardsDeckIdGetRequestParams {
    deckId: string;
}


export interface CardServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    apiCardsCardCardIdGet(requestParameters: ApiCardsCardCardIdGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiCardsCardIdDelete(requestParameters: ApiCardsCardIdDeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiCardsCardIdPut(requestParameters: ApiCardsCardIdPutRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiCardsDeckIdGet(requestParameters: ApiCardsDeckIdGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
*/
    apiCardsGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
*/
    apiCardsPost(extraHttpRequestParams?: any): Observable<{}>;

}
