/**
 * LernApp.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateRequestOfDeckCreateModel } from '../model/models';
import { DeckResponseModel } from '../model/models';
import { ListResponseOfDeckResponseModel } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiDecksDeckIdGetRequestParams {
    deckId: string;
}

export interface ApiDecksPostRequestParams {
    createRequestOfDeckCreateModel: CreateRequestOfDeckCreateModel;
}


export interface DeckServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    apiDecksDeckIdGet(requestParameters: ApiDecksDeckIdGetRequestParams, extraHttpRequestParams?: any): Observable<DeckResponseModel>;

    /**
     * 
     * 
*/
    apiDecksGet(extraHttpRequestParams?: any): Observable<ListResponseOfDeckResponseModel>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiDecksPost(requestParameters: ApiDecksPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
