/**
 * LernApp.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AccountCreateRequest } from '../model/models';
import { AuthResult } from '../model/models';
import { IdentityResponse } from '../model/models';
import { LoginRequest } from '../model/models';
import { LoginResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiIdentityLoginPostRequestParams {
    loginRequest: LoginRequest;
}

export interface ApiIdentityRegisterPostRequestParams {
    accountCreateRequest: AccountCreateRequest;
}


export interface IdentityServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    apiIdentityLoginPost(requestParameters: ApiIdentityLoginPostRequestParams, extraHttpRequestParams?: any): Observable<LoginResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiIdentityRegisterPost(requestParameters: ApiIdentityRegisterPostRequestParams, extraHttpRequestParams?: any): Observable<IdentityResponse>;

    /**
     * 
     * 
*/
    apiIdentityTestGet(extraHttpRequestParams?: any): Observable<AuthResult>;

}
