/**
 * LernApp.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { LearningSessionResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiLearningSessionDeckIdGetRequestParams {
    deckId: string;
}

export interface ApiLearningUpdateCardIdPostRequestParams {
    cardId: string;
    rating?: number;
}


export interface ProgressServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    apiLearningSessionDeckIdGet(requestParameters: ApiLearningSessionDeckIdGetRequestParams, extraHttpRequestParams?: any): Observable<LearningSessionResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiLearningUpdateCardIdPost(requestParameters: ApiLearningUpdateCardIdPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
