/**
 * LernApp.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { StatisticResponseModel } from '../model/models';
import { StatisticSummaryResponseModel } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiStatisticGetRequestParams {
    deckId?: string;
}


export interface StatisticServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    apiStatisticGet(requestParameters: ApiStatisticGetRequestParams, extraHttpRequestParams?: any): Observable<StatisticResponseModel>;

    /**
     * 
     * 
*/
    apiStatisticSummaryGet(extraHttpRequestParams?: any): Observable<StatisticSummaryResponseModel>;

}
